name: test docker build (and tag)

# Controls when the workflow will run
#on: [push]
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: docker build ffmpeg-yours-min      
        run: >
          sh ./build_min.sh  

      - name: docker build ffmpeg-yours
        run: >
          sh ./build_yours.sh  
