name: docker build, then push to DockerHub - [min, debian]

# Controls when the workflow will run
#on: [push]
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: >
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}

      - name: docker build ffmpeg-yours-min (debian)
        run: >
          sh ./build_min_debian.sh --push
