name: test docker build (and tag) - [min]

# Controls when the workflow will run
#on: [push]
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: docker build ffmpeg-yours-min (ubuntu)
        run: >
          sh ./build_min_ubuntu.sh
